---
- name: Configure ELK VM with the Docker
  hosts: elk
  remote_user: sysadmin
  become: true
  tasks:
    - name: Install docker.io
      apt:
        update_cache: yes
        force_apt_get: yes
        name: docker.io
        state: present
    - name: Install python3-pip
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present
    - name: Install the Docker module
      pip:
        name: docker
        state: present
    - name: Increase the Virtual Memory
      command: sysctl -w vm.max_map_count=262144
    - name: Use more Memory
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
        reload: yes
    - name: Download the Docker ELK container and launch
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - '5601:5601'
          - '9200:9200'
          - '5044:5044'
    - name: Enable the service docker on bootup
      systemd:
        name: docker
        enabled: yes